### ISSUE TITLE
Shows sudo password in clear text

### ISSUE THREAD

**Issue by innir** [skx/deployr#14]
Thanks for writing `deployr`!
When using `Sudo` in a recipe `deployr`asks for the password - all fine. But it echos the typed password on the terminal. I think this is dangerous and very unexpected behavior.

**Comment by skx** [comment]
That was a good bug-report, thanks for making it.  (When you reported it I thought "D'oh, that's obvious", yet it hadn't occurred to me.)

Happily it was easy to fix.

**Comment by innir** [comment]
Wow, thanks for the quick fix.

**Comment by skx** [comment]
No worries; I just happened to be online waiting for something else to finish running :)
