### ISSUE TITLE
Detect pageant when running on Windows

### ISSUE THREAD

**Issue by jjeffery** [skx/deployr#24]
When deciding when to use SSH Agent, the environment variable SSH_SOCK_AUTH is checked. This works fine on Unix-based systems but not on Windows. Given that the `simplessh` package uses pageant, it would be good if the Windows version checked for pageant when deciding to use SSH Agent.

**Comment by skx** [comment]
Thanks for your bug-report, and your associated PR.  Things look good, and I'll merge tonight.

Sorry for the slow response, this repository always feels "done" as I've had so little trouble with it, but I do still use it so fixes and improvements are welcome, even if I'm not a Windows user myself!
