### ISSUE TITLE
No support for sudo

### ISSUE THREAD

**Issue by skx** [skx/deployr#8]
We connect as one user - often `root` -  and have no facility for doing things as other users.  Short of the obvious:

    Run "su - nobody -s /bin/sh -c /usr/bin/id"

It might be nice to allow "Sudo" as an alternative to "Run".  Of course if we're prompted for a password it become complex again, quickly..

If we do go down this road we'd need:

* Sudo "command"
* SudoIfChanged "command"

At that point it might be worth taking a step back and removing `IfChanged`, instead adding `If` support.  So we could just run:

    if ( CopyFile .... )  {
       Run "blah"
       Sudo "blah"
    }

Of course that's a slippery slope, but perhaps one worth sliding down.  Comments welcome.

**Comment by bastiao** [comment]
It may be a nice idea to have the "Sudo" command. If it is detected in the recipe, it will be nice ask at first time, in beginning, and execute the sudo commands by that shell, when it is needed. I did not check how it is currently implemented - so I don't have any clue. 

Anyway ask the password, does not allow to automatize scripts and may be only useful in very narrow use cases.

Another nice features - a bit of topic here: 
- it is to have the capability to have few documentation to use deployr in other Go applications. 
- is supports to pass the -i in "ssh" for the private key (could be different in some use cases)

Overall, the goals of the tool are nice.

**Comment by skx** [comment]
I think it should be possible for me to detect ahead of execution if the use of `Sudo` is present.  I'll aim to implement that shortly.

As for use via go-programs, I think that [the godoc](https://godoc.org/github.com/skx/deployr) should be readable, but I suspect I'm not really suited to being used _directly_ by other utilities.  You can see [cmd_run.go](https://github.com/skx/deployr/blob/64c8256f2bf424aa86598707ef4f8725abd6b038/cmd_run.go#L79) has the setup of a deployment - it's a little longer than it should be as it has to sort out:

* lexer
* parser
* evaluator

If people do want to drive the packages via their code I'd support it to the extent that bug-reports come in.

Your idea of allowing `ssh -i ..` (i.e. non-hardwired public-key) is good.  Will report a separate bug to handle that, and ssh-agent, shortly.

Apologies for the delay I've been traveling :)
